# Generated by Django 3.2.2 on 2021-05-12 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mode',
            field=models.CharField(choices=[('fixed-income', 'Renda fixa'), ('variable-income', 'Renda Variável'), ('crypto', 'Cripto Moeda')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='api.asset'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ip_address',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_redemption',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='request_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
